### ISSUE TITLE
Formbuilder

### ISSUE THREAD

**Issue by tbba** [bfncs/TextareaCounter#3] opened 2014-04-29 07:52 UTC
Hi, this modules seems to be not 100% compatible with FormBuilder.
There were tons of php notices with textarea fields in FormBuilder.

(Forgot to pin down the line number before de-installing TextareaCounter...)

**Comment by bfncs** [comment] 2014-04-29 07:58
Thanks a lot for testing this.

Sadly I don't use FormBuilder and therefore haven't bought it, so I cant test this myself. It would be great to get some more specific bug report (or even better: pull request), so this can be fixed.

**Comment by tbba** [comment] 2014-04-29 08:32
I was half expecting this :-)
I installed the module again and got this:
(Formbuilder 0.2.3, PW 2.4.1dev latest)

Notice: Trying to get property of non-object in /......./site/modules/TextareaCounter/TextareaCounter.module on line 50

Notice: Trying to get property of non-object in /......./site/modules/TextareaCounter/TextareaCounter.module on line 58

Notice: Trying to get property of non-object in /......./site/modules/TextareaCounter/TextareaCounter.module on line 66

Notice: Trying to get property of non-object in /......./site/modules/TextareaCounter/TextareaCounter.module on line 50

Notice: Trying to get property of non-object in /......./site/modules/TextareaCounter/TextareaCounter.module on line 58

Notice: Trying to get property of non-object in /......./site/modules/TextareaCounter/TextareaCounter.module on line 66

**Comment by bfncs** [comment] 2014-04-29 16:14
Thanks a lot for posting the notices!

So, I can't test it, but looking at the lines referred to, so I would guess the problem is that when called  by FormBuilder, `$event->object` is not defined as the field itself but something else. Without properly debugging it or at least looking at the code it's nearly impossible to get this right, whatsoever.

What might help would be if you either:
- debug the code and check exactly what's not working here,
- check whether FormBuilder defines a hook for `InputfieldTextarea::getConfigInputfields` and if yes send me that snippet so I can have a look, or
- kindly ask Ryan whether he has any interest to look into it.

**Comment by tbba** [comment] 2014-05-19 19:41
The bug also appears at other places, not only the formbuilder, for instance the PafefieldselectCreator module. The bug seems to come up if the API creates fields instead of the user and some values do not exist to prefill your admin fields.

I built a clone and tested it.

The errors go away if you test with ISSET at the 3 occurrences, like so;

if (isset($this->fields->get($event->object->name)->maxchars)) { 
            $value = $this->fields->get($event->object->name)->maxchars;
        } else {
            $value = '';
        }
        $f->attr('value', $value ? $value : '');

Maybe there are more clever ways (I am not a coder) but it works fine so war.

("wontfix" is a not very encouraging label to believe in the module and it's future, by the way :-)

**Comment by bfncs** [comment] 2014-05-22 10:27
Thanks a lot for looking into this, @tbba!

You gave me some very valuable pointer, especially about checking it with other modules like PagefieldSelectCreator. I'm currently on vacation, but I'm going to look into this when I'm back. Taking back the "wontfix" for now. ;-)

**Comment by owzim** [comment] 2014-11-03 13:15
I am not sure if it's the same issue or a different, but those notices appear on `ProcessPageEdit` with fields that are of type `FieldtypeMultiplier` too:

```
( ! ) Notice: Trying to get property of non-object in /site/modules/TextareaCounter/TextareaCounter.module on line 104
Call Stack
#   Time    Memory  Function    Location
1   0.0004  283800  {main}( )   ../index.php:0
2   0.1408  11412544    execute ( ) ../index.php:214
3   0.1408  11412896    Wire->__call( ) ../index.php:214
4   0.1408  11413152    Wire->runHooks( )   ../Wire.php:344
5   0.1408  11415024    call_user_func_array:{/wire/core/Wire.php:389} ( )  ../Wire.php:389
6   0.1408  11416312    ProcessPageView->___execute( )  ../Wire.php:389
7   0.1596  12612320    render ( )  ../ProcessPageView.module:171
8   0.1596  12612504    Wire->__call( ) ../ProcessPageView.module:171
9   0.1596  12612504    Wire->runHooks( )   ../Wire.php:344
10  0.1597  12625688    renderPage ( )  ../Wire.php:411
11  0.1597  12626040    Wire->__call( ) ../Wire.php:411
12  0.1597  12626296    Wire->runHooks( )   ../Wire.php:344
13  0.1597  12628168    call_user_func_array:{/wire/core/Wire.php:389} ( )  ../Wire.php:389
14  0.1597  12629728    PageRender->___renderPage( )    ../Wire.php:389
15  0.1604  12696120    render ( )  ../PageRender.module:356
16  0.1604  12696304    Wire->__call( ) ../PageRender.module:356
17  0.1604  12696560    Wire->runHooks( )   ../Wire.php:344
18  0.1604  12698432    call_user_func_array:{/wire/core/Wire.php:389} ( )  ../Wire.php:389
19  0.1604  12698936    TemplateFile->___render( )  ../Wire.php:389
20  0.1606  12724584    require( '/site/templates/admin.php' )  ../TemplateFile.php:169
21  0.1606  12726152    require( '/wire/modules/AdminTheme/AdminThemeDefault/controller.php' )  ../admin.php:15
22  0.1609  12762016    require( '/wire/core/admin.php' )   ../controller.php:13
23  0.1642  13051560    execute ( ) ../admin.php:85
24  0.1642  13051744    Wire->__call( ) ../admin.php:85
25  0.1642  13052000    Wire->runHooks( )   ../Wire.php:344
26  0.1642  13053872    call_user_func_array:{/wire/core/Wire.php:389} ( )  ../Wire.php:389
27  0.1642  13054416    ProcessController->___execute( )    ../Wire.php:389
28  0.1739  13744512    execute ( ) ../ProcessController.php:204
29  0.1739  13744696    Wire->__call( ) ../ProcessController.php:204
30  0.1739  13744952    Wire->runHooks( )   ../Wire.php:344
31  0.1762  13751336    call_user_func_array:{/wire/core/Wire.php:389} ( )  ../Wire.php:389
32  0.1762  13752080    ProcessPageEdit->___execute( )  ../Wire.php:389
33  0.2346  16213360    ProcessPageEdit->renderEdit( )  ../ProcessPageEdit.module:125
34  0.2428  16220648    render ( )  ../ProcessPageEdit.module:144
35  0.2428  16220832    Wire->__call( ) ../ProcessPageEdit.module:144
36  0.2428  16221088    Wire->runHooks( )   ../Wire.php:344
37  0.2606  16225904    call_user_func_array:{/wire/core/Wire.php:389} ( )  ../Wire.php:389
38  0.2606  16226368    InputfieldForm->___render( )    ../Wire.php:389
39  0.2842  16290800    InputfieldWrapper->___render( ) ../InputfieldForm.module:57
40  0.3068  16300504    render ( )  ../InputfieldWrapper.php:287
41  0.3068  16300688    Wire->__call( ) ../InputfieldWrapper.php:287
42  0.3069  16300944    Wire->runHooks( )   ../Wire.php:344
43  0.3069  16302816    call_user_func_array:{/wire/core/Wire.php:389} ( )  ../Wire.php:389
44  0.3069  16302984    InputfieldWrapper->___render( ) ../Wire.php:389
45  0.3166  16314280    render ( )  ../InputfieldWrapper.php:287
46  0.3166  16314464    Wire->__call( ) ../InputfieldWrapper.php:287
47  0.3166  16314720    Wire->runHooks( )   ../Wire.php:344
48  0.3167  16316592    call_user_func_array:{/wire/core/Wire.php:389} ( )  ../Wire.php:389
49  0.3167  16318232    InputfieldWrapper->___render( ) ../Wire.php:389
50  0.3688  16578168    render ( )  ../InputfieldWrapper.php:287
51  0.3688  16578352    Wire->__call( ) ../InputfieldWrapper.php:287
52  0.3688  16578608    Wire->runHooks( )   ../Wire.php:344
53  0.3691  16583976    call_user_func_array:{/wire/core/Wire.php:389} ( )  ../Wire.php:389
54  0.3691  16584424    InputfieldMultiplier->___render( )  ../Wire.php:389
55  0.3696  16585608    InputfieldMultiplier->renderItem( ) ../InputfieldMultiplier.module:89
56  0.3723  16849912    render ( )  ../InputfieldMultiplier.module:124
57  0.3723  16850096    Wire->__call( ) ../InputfieldMultiplier.module:124
58  0.3723  16981336    Wire->runHooks( )   ../Wire.php:344
59  0.3727  16986664    TextareaCounter->renderBeforeTextarea( )    ../Wire.php:411
```

**Closed as completed** 2014-11-10 17:21 UTC
Labels: bug
